---
- name: Vérifier si le dépôt existe déjà
  stat:
    path: '{{ projet_dir }}/cookiecutter-django-vue-graphql-aws'
  register: repo_exists

- name: Vérifier si le venv '{{ venv_name }}' existe déjà
  stat:
    path: '{{ projet_dir }}/{{  venv_name }}'
  register: venv_exists

- name: Vérifier si le projet django '{{ project_name }}' existe déjà
  stat:
    path: "{{ projet_dir }}/{{ project_slug }}"
  register: project_exists

- name: Cloner le dépôt cookiecutter-django-vue-graphql-aws
  git:
    repo: 'https://github.com/grantmcconnaughey/cookiecutter-django-vue-graphql-aws.git'
    dest: '{{ projet_dir }}/cookiecutter-django-vue-graphql-aws'
  when: not repo_exists.stat.exists

- name: Modifier le fichier cookiecutter.json
  copy:
    content: |
      {
        "project_name": "{{ project_name }}",
        "project_slug": "{{ project_slug }}",
        "author_name": "{{ author_name }}",
        "domain_name": "{{ domain_name }}",
        "email": "{{ email }}",
        "version": "{{ version }}"
      }
    dest: "{{ projet_dir }}/cookiecutter-django-vue-graphql-aws/cookiecutter.json"

- name: Créer un environnement virtuel
  command: python3 -m venv {{ projet_dir }}/{{ venv_name }}
  when: not venv_exists.stat.exists

- name: Activer l'environnement virtuel et installer Cookiecutter
  shell: |
    source {{ projet_dir }}/{{ venv_name }}/bin/activate
    pip install cookiecutter
  args:
    executable: /bin/bash

- name: Exécuter cookiecutter pour générer le projet
  shell: |
    source {{ projet_dir }}/{{ venv_name }}/bin/activate
    cookiecutter --no-input {{ projet_dir }}/cookiecutter-django-vue-graphql-aws
  environment:
    project_name: "{{ project_name }}"
    author_name: "{{ author_name }}"
    domain_name: "{{ domain_name }}"
    email: "{{ email }}"
    version: "{{ version }}"
  args:
    chdir: '{{ projet_dir }}'
    executable: /bin/bash
  when: not project_exists.stat.exists

- name: Supprimer le repo git matrice
  command: rm -fr {{ projet_dir }}/cookiecutter-django-vue-graphql-aws

- name: Supprimer le repo git matrice 2
  command: rm -fr {{ home_dir }}/{{ project_slug }}

- name: owner {{ user }}
  command: 'chown -R {{ user }}: {{ projet_dir }}'

- name: chmod 744
  command: 'chmod -R 744 {{ projet_dir }}'


- name: Construire et démarrer les conteneurs Docker
  shell: |
    source {{ projet_dir }}/{{ venv_name }}/bin/activate
    docker compose up --build -d
  args:
    chdir: "{{ projet_dir }}/{{ project_slug }}"
    executable: /bin/bash