---
- name: Check if cloned project already exists
  stat:
    path: '{{ projet_dir }}/{{ cookiecutter_original }}'
  register: repo_exists

- name: Check if venv '{{ venv_name }}' already exists
  stat:
    path: '{{ projet_dir }}/{{  venv_name }}'
  register: venv_exists

- name: Check if project '{{ project_name }}' already exists
  stat:
    path: "{{ projet_dir }}/{{ project_slug }}"
  register: project_exists

- name: Clone repo {{ git_project }}
  git:
    repo: '{{ git_project }}'
    dest: '{{ projet_dir }}/{{ cookiecutter_original }}'
  when: not repo_exists.stat.exists

- name: Edit file cookiecutter.json
  copy:
    content: |
      {
        "project_name": "{{ project_name }}",
        "project_slug": "{{ project_slug }}",
        "author_name": "{{ author_name }}",
        "domain_name": "{{ domain_name }}",
        "email": "{{ email }}",
        "version": "{{ version }}",
        "postgres_version": "{{ postgres_version }}",
        "python_version": "{{ python_version }}",
        "node_version": "{{ node_version }}"
      }
    dest: "{{ projet_dir }}/{{ cookiecutter_original }}/cookiecutter.json"

- name: Create venv {{ venv_name }}
  command: python3 -m venv {{ projet_dir }}/{{ venv_name }}
  when: not venv_exists.stat.exists

- name: source env & install cookiecutter
  shell: |
    source {{ projet_dir }}/{{ venv_name }}/bin/activate
    pip install cookiecutter
  args:
    executable: /bin/bash

- name: Generate the project
  shell: |
    source {{ projet_dir }}/{{ venv_name }}/bin/activate
    cookiecutter --no-input {{ projet_dir }}/{{ cookiecutter_original }}
  environment:
    project_name: "{{ project_name }}"
    author_name: "{{ author_name }}"
    domain_name: "{{ domain_name }}"
    email: "{{ email }}"
    version: "{{ version }}"
    postgres_version": "{{ postgres_version }}"
    python_version": "{{ python_version }}"
    node_version": "{{ node_version }}"
  args:
    chdir: '{{ projet_dir }}'
    executable: /bin/bash
  when: not project_exists.stat.exists

- name: Remove cloned project
  command: rm -fr {{ projet_dir }}/{{ cookiecutter_original }}

- name: Remove artifacts
  command: rm -fr {{ home_dir }}/{{ project_slug }}

- name: owner {{ user }}
  command: 'chown -R {{ user }}: {{ projet_dir }}'

- name: chmod 744
  command: 'chmod -R 744 {{ projet_dir }}'

- name: Start containers detached
  shell: |
    source {{ projet_dir }}/{{ venv_name }}/bin/activate
    docker compose up --build -d
  args:
    chdir: "{{ projet_dir }}/{{ project_slug }}"
    executable: /bin/bash