---
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true

- name: mkdir keyrings APT
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Get docker GPG key
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
  become: true

- name: chmod 644
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add repo Docker sources APT
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  become: true

- name: Upd apt
  apt:
    update_cache: yes
  become: true

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: true

- name: remove python-configparser
  apt:
    name: python-configparser
    state: absent
  become: true

- name: Download docker sh
  shell: curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  args:
    creates: /tmp/get-docker.sh
  become: true

- name: Install Docker
  shell: sh /tmp/get-docker.sh
  args:
    creates: /usr/bin/docker
  become: true

- name: Add user to group docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Check install Docker
  command: docker --version
  register: docker_version

- name: Check install Docker Compose
  command: docker compose --version
  register: docker_compose_version

