---
- name: Vérifier et configurer les paquets interrompus
  command: sudo dpkg --configure -a
  changed_when: false
  failed_when: false
  async: "{{ timeout_default }}"
  poll: 0

- name: Mise à jour et mise à niveau des paquets
  apt:
    update_cache: yes
    upgrade: dist
  async: "{{ timeout_default }}"
  poll: 0

- name: Install Basic tools
  apt:
    name:
      - git
      - vim
      - build-essential
      - cmake
    state: present
  async: "{{ timeout_default }}"
  poll: 0

- name: Install Python
  apt:
    name: 
      - python3
      - python3-pip
      - python3-venv
    state: present
  async: "{{ timeout_default }}"
  poll: 0
