---
- name: Check stopped packages
  command: sudo dpkg --configure -a
  changed_when: false
  failed_when: false
  async: "{{ timeout_default }}"
  poll: 0

- name: Update apt
  apt:
    update_cache: yes
    upgrade: dist
  async: "{{ timeout_default }}"
  poll: 0

- name: Install Basic tools
  apt:
    name:
      - git
      - vim
      - build-essential
      - cmake
    state: present
  async: "{{ timeout_default }}"
  poll: 0

- name: Install Python
  apt:
    name: 
      - python3
      - python3-pip
      - python3-venv
    state: present
  async: "{{ timeout_default }}"
  poll: 0

- name: Configure Git for user {{ git_name }}
  command: git config --global user.name "{{ git_name }}" && git config --global user.email "{{ git_email }}" && git config --global credential.helper store
  async: "{{ timeout_default }}"
  poll: 0
